### ISSUE TITLE
Users must NOT be able to see other users submissions

### ISSUE THREAD

**Issue by olivierobert** [hoangmirs/google_scraper#17]
![list_search_results___google_scraper_and___link_to_launch_ios_simulator_on_nimbl3_growth](https://user-images.githubusercontent.com/696529/46520968-2f64db80-c8a8-11e8-90fa-2969e6647111.png)

As part of authorization, users should only be able to see their own search results. Gems like Pundit are a good way to implement this easily in a Rails application.

**Comment by hoangmirs** [comment]
Thank you, I will edit it.
Because I let all users can see search results each other so I added search by column.

**Comment by hoangmirs** [comment]
I added it in #18
