### ISSUE TITLE
Prefer moving SQL queries to Query Objects

### ISSUE THREAD

**Issue by olivierobert** [hoangmirs/google_scraper#24]
![hoang___volumes_workspace__candidates-tests_hoang__-_____app_models_link_rb__hoang_](https://user-images.githubusercontent.com/696529/46595399-62a2a700-cb02-11e8-9cb1-350863be381a.png)

Models can get quite crowded with lots of different methods to query data making them hard to test and maintain. Instead, usee Query Objects and use them in the context where these methods are required. For instance, the query to fetch string occurrences is only used only once so it does not need to be in the model itself.

**Comment by hoangmirs** [comment]
I moved it to LinksQuery in #27
