### ISSUE TITLE
Too long method so externalize to smaller methods

### ISSUE THREAD

**Issue by olivierobert** [hoangmirs/google_scraper#26]
![hoang___volumes_workspace__candidates-tests_hoang__-_____app_services_scraper_service_rb__hoang_](https://user-images.githubusercontent.com/696529/46595655-b1047580-cb03-11e8-9705-63b6e2f8fe7e.png)

Linters and code analyzers like Rubocop would have screamed at you for such long methods 😵 Prefer having short methods (< 5-8 lines) by externalizing the same logic to smaller methods:

```ruby
def save_search_result
  collect_link_attributes
  result = SearchResult.create! 
    keyword: keyword,
    total_results: total_results,
    total_links: total_links, html_code: html_code, user_id: user_id,
    links_attributes: links_attributes,
    server_ip: server_ip, user_agent: @user_agent
rescue Exception => error
  @error = error.message
  $stderr.puts "Save search result failed: #{error.message}"
end

def collect_link_attributes
  collect_non_ads_links
  collect_top_ads_links
  collect_bottom_ads_links
end

#...
```

**Comment by hoangmirs** [comment]
I refactored the service in #28
